;;; yank-as-markdown.el --- Yank kill-ring text converted to Markdown -*- lexical-binding: t; -*-

;; Generated by AI Sloperator (https://www.aisloperator.com)
;; using Claude Fable 5 High, starting on July 11, 2026.

;; Author: (your name here)
;; Version: 0.1
;; Keywords: convenience, wp, markdown
;; Package-Requires: ((emacs "26.1"))

;;; Commentary:

;; This library provides the command `yank-as-markdown', which inserts
;; the same text that `yank' would insert (the head of the kill ring,
;; which normally reflects the system clipboard), but first runs it
;; through a series of heuristics to convert it to Markdown.
;;
;; Heuristics currently implemented, tried in this order:
;;
;;   1. Thunderbird forwarded message -- text beginning with
;;      "-------- Forwarded Message --------".  The email headers are
;;      wrapped in a ``` fenced code block and every body line is
;;      quoted with the Markdown "> " prefix.
;;
;;   2. HTML -- obvious headings, paragraphs, links, bold, and italics
;;      are converted to their Markdown equivalents; most other markup
;;      is stripped, and a handful of common character entities are
;;      decoded.
;;
;;   3. Markdown -- text that already looks like Markdown is lightly
;;      normalized: a blank line is guaranteed between consecutive
;;      bulleted or numbered list items, and "-" bullet markers are
;;      rewritten as "*".
;;
;;   4. Plain text (fallback) -- minimal conversion: a hard line break
;;      that is *not* the end of a paragraph (i.e. a newline whose next
;;      line is non-blank) gets an explicit "<br>" appended so the
;;      break survives Markdown rendering.
;;
;; The dispatch table lives in `yank-as-markdown-heuristics'; new
;; heuristics can be added over time by pushing (PREDICATE . CONVERTER)
;; pairs onto that list.
;;
;; Usage:
;;
;;   (require 'yank-as-markdown)
;;   M-x yank-as-markdown
;;
;; or bind it, e.g.:
;;
;;   (global-set-key (kbd "C-c C-y") #'yank-as-markdown)

;;; Code:

;;;; Customization ------------------------------------------------------

(defgroup yank-as-markdown nil
  "Yank kill-ring text converted to Markdown."
  :group 'convenience
  :prefix "yank-as-markdown-")

(defcustom yank-as-markdown-announce t
  "If non-nil, echo which heuristic was applied after inserting."
  :type 'boolean
  :group 'yank-as-markdown)

;;;; Small utilities ----------------------------------------------------

(defun yank-as-markdown--collapse-blank-lines (text)
  "Collapse runs of 3 or more newlines in TEXT down to exactly 2.
Also trims leading and trailing whitespace.  Used to tidy up the
output of the converters, which are free to be sloppy about the
blank lines they emit."
  (string-trim (replace-regexp-in-string "\n\\{3,\\}" "\n\n" text)))

(defun yank-as-markdown--decode-entities (text)
  "Decode a handful of common HTML character entities in TEXT.
This is deliberately not a full entity decoder; it just handles
the entities that show up constantly in copied web text.  Note
that \"&amp;\" is decoded last so that e.g. \"&amp;lt;\" does not
turn into \"<\"."
  (dolist (pair '(("&nbsp;" . " ")
                  ("&lt;"   . "<")
                  ("&gt;"   . ">")
                  ("&quot;" . "\"")
                  ("&#39;"  . "'")
                  ("&apos;" . "'")
                  ("&mdash;" . "---")
                  ("&ndash;" . "--")
                  ("&hellip;" . "...")
                  ("&amp;"  . "&")))          ; keep last -- see docstring
    (setq text (replace-regexp-in-string
                (regexp-quote (car pair)) (cdr pair) text t t)))
  text)

;;;; Heuristic 1: Thunderbird forwarded message -------------------------

(defconst yank-as-markdown--thunderbird-marker
  "-------- Forwarded Message --------"
  "The line Thunderbird places at the top of a forwarded message.")

(defun yank-as-markdown--thunderbird-p (text)
  "Return non-nil if TEXT looks like a Thunderbird message forward.
Matches when TEXT begins (possibly after leading whitespace) with
`yank-as-markdown--thunderbird-marker'."
  (string-match-p
   (concat "\\`[ \t\n]*" (regexp-quote yank-as-markdown--thunderbird-marker))
   text))

(defun yank-as-markdown--convert-thunderbird (text)
  "Convert a Thunderbird forwarded message TEXT to Markdown.
The marker line and the header block that follows it (everything
up to the first blank line) are placed inside a ``` fenced code
block so the headers render verbatim.  Every line of the message
body is prefixed with \"> \" so the body renders as a Markdown
block quote.  Blank body lines get a bare \">\" so the quote is
not broken into separate blocks."
  (let* ((lines (split-string (string-trim-left text) "\n"))
         (headers '())
         (body '())
         (in-headers t))
    (dolist (line lines)
      (if in-headers
          ;; The header block ends at the first blank line.
          (if (string-match-p "\\`[ \t]*\\'" line)
              (setq in-headers nil)
            (push line headers))
        (push line body)))
    ;; Drop trailing blank lines from the body so we don't emit a
    ;; dangling run of bare ">" markers at the end.
    (while (and body (string-match-p "\\`[ \t]*\\'" (car body)))
      (pop body))
    (concat "```\n"
            (mapconcat #'identity (nreverse headers) "\n")
            "\n```\n\n"
            (mapconcat (lambda (line)
                         (if (string-match-p "\\`[ \t]*\\'" line)
                             ">"
                           (concat "> " line)))
                       (nreverse body)
                       "\n"))))

;;;; Heuristic 2: HTML ---------------------------------------------------

(defun yank-as-markdown--html-p (text)
  "Return non-nil if TEXT looks like HTML.
The test is intentionally cheap: we look for any of the tags this
converter knows how to handle (headings, paragraphs, anchors,
bold, italics, breaks, lists, divs) or an <html>/<body> wrapper."
  (let ((case-fold-search t))
    (string-match-p
     (concat "<\\(?:html\\|body\\|div\\|p\\|br\\|h[1-6]\\|a[ \t\n]"
             "\\|b>\\|strong\\|i>\\|em\\|ul\\|ol\\|li\\)")
     text)))

(defun yank-as-markdown--convert-html (text)
  "Convert HTML TEXT to Markdown.
Handles the obvious cases:
  <h1>..<h6>        ->  #, ##, ... ###### headings
  <p>               ->  paragraphs separated by blank lines
  <a href=\"URL\">  ->  [text](URL)
  <b>, <strong>     ->  **bold**
  <i>, <em>         ->  *italics*
  <br>              ->  hard newline
  <li>              ->  \"* \" bullet (crude, but useful)
All other tags -- along with <script>, <style>, and comment
blocks in their entirety -- are stripped.  A few common character
entities are decoded at the end."
  (with-temp-buffer
    (insert text)
    (let ((case-fold-search t))
      ;; -- Remove content that should never appear in output. --------
      (dolist (re '("<script\\(?:.\\|\n\\)*?</script[^>]*>"
                    "<style\\(?:.\\|\n\\)*?</style[^>]*>"
                    "<!--\\(?:.\\|\n\\)*?-->"
                    "<head\\(?:.\\|\n\\)*?</head[^>]*>"))
        (goto-char (point-min))
        (while (re-search-forward re nil t)
          (replace-match "" t t)))
      ;; -- Inline elements first, while their tags are still intact. -
      ;; Links: <a ... href="URL" ...>TEXT</a>  ->  [TEXT](URL)
      (goto-char (point-min))
      (while (re-search-forward
              "<a\\b[^>]*href=[\"']\\([^\"']*\\)[\"'][^>]*>\\(\\(?:.\\|\n\\)*?\\)</a[^>]*>"
              nil t)
        (replace-match "[\\2](\\1)" t nil))
      ;; Bold: <b> / <strong>
      (goto-char (point-min))
      (while (re-search-forward
              "<\\(?:b\\|strong\\)\\b[^>]*>\\(\\(?:.\\|\n\\)*?\\)</\\(?:b\\|strong\\)[^>]*>"
              nil t)
        (replace-match "**\\1**" t nil))
      ;; Italics: <i> / <em>
      (goto-char (point-min))
      (while (re-search-forward
              "<\\(?:i\\|em\\)\\b[^>]*>\\(\\(?:.\\|\n\\)*?\\)</\\(?:i\\|em\\)[^>]*>"
              nil t)
        (replace-match "*\\1*" t nil))
      ;; -- Block-level elements. --------------------------------------
      ;; Headings: <hN>TEXT</hN> -> N hash marks.  Done via a loop with
      ;; an explicit replacement because the number of "#" characters
      ;; depends on the captured level.
      (goto-char (point-min))
      (while (re-search-forward
              "<h\\([1-6]\\)\\b[^>]*>\\(\\(?:.\\|\n\\)*?\\)</h[1-6][^>]*>"
              nil t)
        (let ((level (string-to-number (match-string 1)))
              (body  (string-trim (match-string 2))))
          (replace-match
           (concat "\n\n" (make-string level ?#) " " body "\n\n")
           t t)))
      ;; List items: a crude "* " bullet.  (Nested/ordered lists are a
      ;; future heuristic refinement.)
      (goto-char (point-min))
      (while (re-search-forward "<li\\b[^>]*>" nil t)
        (replace-match "\n* " t t))
      ;; Paragraphs and structural breaks become blank lines.
      (goto-char (point-min))
      (while (re-search-forward
              "</?\\(?:p\\|div\\|ul\\|ol\\|blockquote\\|table\\|tr\\)\\b[^>]*>"
              nil t)
        (replace-match "\n\n" t t))
      ;; <br> becomes a plain newline.
      (goto-char (point-min))
      (while (re-search-forward "<br\\b[^>]*/?>" nil t)
        (replace-match "\n" t t))
      ;; -- Strip everything else that still looks like a tag. ---------
      (goto-char (point-min))
      (while (re-search-forward "</?[a-zA-Z][^>]*>" nil t)
        (replace-match "" t t)))
    (yank-as-markdown--collapse-blank-lines
     (yank-as-markdown--decode-entities (buffer-string)))))

;;;; Heuristic 3: already Markdown ---------------------------------------

(defun yank-as-markdown--list-item-p (line)
  "Return non-nil if LINE looks like a Markdown list item.
Recognizes bulleted items (\"-\", \"*\", \"+\") and numbered
items (\"1.\", \"2)\", ...), with optional leading indentation."
  (string-match-p "\\`[ \t]*\\(?:[-*+]\\|[0-9]+[.)]\\)[ \t]" line))

(defun yank-as-markdown--markdown-p (text)
  "Return non-nil if TEXT already looks like Markdown.
Cheap signals: an ATX heading, a list item, a fenced code block,
or an inline [link](url)."
  (or (string-match-p "^#\\{1,6\\} " text)
      (string-match-p "^```" text)
      (string-match-p "\\[[^]\n]+\\]([^)\n]+)" text)
      (let ((match nil))
        (dolist (line (split-string text "\n") match)
          (when (yank-as-markdown--list-item-p line)
            (setq match t))))))

(defun yank-as-markdown--convert-markdown (text)
  "Normalize Markdown TEXT to house style.
Two tweaks are applied:
  1. \"-\" bullet markers are rewritten as \"*\" (indentation is
     preserved).
  2. A blank line is guaranteed between consecutive list items,
     whether bulleted or numbered.
Lines inside ``` fenced code blocks are left completely alone."
  (let ((lines (split-string text "\n"))
        (out '())
        (in-fence nil))
    (while lines
      (let* ((line (pop lines))
             (next (car lines)))
        ;; Track fenced code blocks so we never touch their contents.
        (when (string-match-p "\\`[ \t]*```" line)
          (setq in-fence (not in-fence))
          (push line out)
          (setq line nil))
        (when line
          (unless in-fence
            ;; Tweak 1: "-" bullets become "*" bullets.
            (setq line (replace-regexp-in-string
                        "\\`\\([ \t]*\\)-\\([ \t]\\)" "\\1*\\2" line)))
          (push line out)
          ;; Tweak 2: blank line between adjacent list items.
          (when (and (not in-fence)
                     next
                     (yank-as-markdown--list-item-p line)
                     (yank-as-markdown--list-item-p next))
            (push "" out)))))
    (mapconcat #'identity (nreverse out) "\n")))

;;;; Heuristic 4 (fallback): plain text -----------------------------------

(defun yank-as-markdown--convert-plain (text)
  "Minimally convert plain TEXT to Markdown.
The only transformation is appending \"<br>\" to any non-blank
line that is immediately followed by another non-blank line --
i.e. a line break that is not the termination of a paragraph.
Without this, Markdown renderers would join such lines into a
single flowing paragraph and the break would be lost.  Paragraph
breaks (blank lines) are left as-is."
  (let ((lines (split-string text "\n"))
        (out '()))
    (while lines
      (let ((line (pop lines))
            (next (car lines)))
        (push (if (and next
                       (not (string-match-p "\\`[ \t]*\\'" line))
                       (not (string-match-p "\\`[ \t]*\\'" next)))
                  (concat line "<br>")
                line)
              out)))
    (mapconcat #'identity (nreverse out) "\n")))

;;;; Dispatch --------------------------------------------------------------

(defvar yank-as-markdown-heuristics
  (list (cons #'yank-as-markdown--thunderbird-p
              #'yank-as-markdown--convert-thunderbird)
        (cons #'yank-as-markdown--html-p
              #'yank-as-markdown--convert-html)
        (cons #'yank-as-markdown--markdown-p
              #'yank-as-markdown--convert-markdown))
  "Alist of (PREDICATE . CONVERTER) heuristics, tried in order.
Each PREDICATE is called with the raw kill-ring text and should
return non-nil if its CONVERTER applies.  The first match wins.
If no heuristic matches, `yank-as-markdown--convert-plain' is
used as the fallback.

To add a new heuristic over time, push a new pair onto this list
\(or `add-to-list' at the appropriate position -- order matters,
since more specific detectors should run before more general
ones).")

(defun yank-as-markdown--convert (text)
  "Convert TEXT to Markdown using `yank-as-markdown-heuristics'.
Returns a cons cell (NAME . CONVERTED), where NAME is a short
string describing the heuristic that matched (for user feedback)
and CONVERTED is the resulting Markdown string."
  (let ((entry (seq-find (lambda (pair) (funcall (car pair) text))
                         yank-as-markdown-heuristics)))
    (if entry
        (cons (symbol-name (cdr entry))
              (funcall (cdr entry) text))
      (cons "plain text (fallback)"
            (yank-as-markdown--convert-plain text)))))

;;;; The command -----------------------------------------------------------

;;;###autoload
(defun yank-as-markdown ()
  "Insert the most recent kill, converted to Markdown.
This inserts the same text that `yank' would insert (the head of
the kill ring, which normally reflects the system clipboard), but
first runs it through the heuristics in
`yank-as-markdown-heuristics':

  1. A Thunderbird \"-------- Forwarded Message --------\" paste
     gets its headers fenced in a code block and its body quoted
     with \"> \".
  2. HTML has headings, paragraphs, links, bold, and italics
     converted to Markdown, with other markup stripped.
  3. Text that is already Markdown is normalized: blank lines
     between list items, and \"*\" bullets instead of \"-\".
  4. Anything else is treated as plain text; intra-paragraph line
     breaks get an explicit \"<br>\" so they survive rendering.

Mark is pushed at the insertion point, as with `yank', so
\\[exchange-point-and-mark] jumps back to the start of the
inserted text."
  (interactive "*")
  (let ((text (current-kill 0)))
    (unless (and text (> (length text) 0))
      (user-error "Kill ring is empty"))
    (let ((result (yank-as-markdown--convert text)))
      (push-mark)
      (insert (cdr result))
      (when yank-as-markdown-announce
        (message "yank-as-markdown: applied %s" (car result))))))

(provide 'yank-as-markdown)

;;; yank-as-markdown.el ends here
